# Generated by Django 6.0.4 on 2026-04-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_product_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="featured",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
